remote_theme: WildCodeSchool/workshops-jekyll-theme

titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

style: dev
title: Deploy 01 - Vanilla
description: "How to deploy a vanilla sites with the base code hosted on GitHub."
show_clone: false
show_toc: true
lang: en
